### ISSUE TITLE
Allow save/saveDev/saveExact behavior to be customized based on context

### ISSUE THREAD

**Issue by bebraw** [ericclemmons/npm-install-webpack-plugin#22]
It would be good if there were some kind of hooks in place that would allow you to decide what kind of save to apply given a package within some location.

The reason for this is that I prefer to keep strict separation between `dependencies` and `devDependencies`. For example all `./app` dependencies would go to the former category whereas the rest would go to the latter.

It would be enough for me if there was a callback that received the context where an import was detected. I could then return the type of save based on that.

What do you think? If you are busy, I can try to craft a PR. Apart from this, the plugin works very well.

**Comment by ericclemmons** [comment]
Sounds a lot like #13.

**Comment by bebraw** [comment]
Yeah, I'll close this and continue the conversation there.
