### ISSUE TITLE
Working with relative imports using 'resolve'

### ISSUE THREAD

**Issue by adamkleingit** [ericclemmons/npm-install-webpack-plugin#24]
When working with webpack, we use resolve, as such:
```
  resolve: {
    // Enable resolving modules relative to these paths
    root: [path.join(__dirname, 'lib')],
  }
```
Then import files like so:
import state from 'api/state';

The problem is that npm-install-webpack-plugin tries to install the node module called api.

I would suggest only installing files that webpack can't resolve (maybe there's a hook for that?).

**Comment by ericclemmons** [comment]
I do the same thing, and this is already tracked here #17.
