### ISSUE TITLE
Seems to add extra packages to package.json

### ISSUE THREAD

**Issue by bmakuh** [ericclemmons/npm-install-webpack-plugin#26]
Super cool idea, by the way. But I'm trying it out and it seems like it's adding the dependencies of my dependencies to package.json. For instance, `cheerio` is a dependency of `enzyme`, and I'm using enzyme in my app. But `npm-install-webpack-plugin` installed cheerio into my package.json even though I'm not relying on it directly.

**Comment by ericclemmons** [comment]
Weird.  I do a check to ignore any sub-modules that are in `node_modules`.

- [ ] Test dependency installation of `cheerio`.

**Comment by satya164** [comment]
Also seemed to install `babel-loader` as well as `webpack-hot-middleware` into my project. They are dependencies of a server located in a different directory.

**Comment by ericclemmons** [comment]
Different directory?  Which directory is it?  You have a `package.json` in
your project right?

On Tue, Feb 9, 2016 at 2:30 PM Satyajit Sahoo <notifications@github.com>
wrote:

> Also seemed to install babel-loader as well as webpack-hot-middleware
> into my project. They are dependencies of a server located in a different
> directory.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ericclemmons/npm-install-webpack-plugin/issues/26#issuecomment-182048025>
> .
>
-- 
- Eric Clemmons

**Comment by satya164** [comment]
@ericclemmons The modules folder was specified using the resolveLoader.root option of webpack (both the dependencies are for the server and they were missing). The actual project is in a different directory.

**Comment by satya164** [comment]
Trying to integrate with - https://github.com/satya164/quik , which is a server to do dev without setup.

**Comment by ericclemmons** [comment]
Ah, now I see.  Yep, this is a problem until #17 is finished up.  I'm launching a project this week, so I should be able to finalize the next release soon.

Sorry for the delay!

**Comment by satya164** [comment]
@ericclemmons Ah. Cool. Thanks :)

**Comment by ericclemmons** [comment]
@satya164 Wanna check this out with v3.0.0?

**Comment by satya164** [comment]
@ericclemmons Will do soon. Thank you.

**Comment by ericclemmons** [comment]
Re-open if it's an issue!
