### ISSUE TITLE
Exclude some packages

### ISSUE THREAD

**Issue by radubrehar** [ericclemmons/npm-install-webpack-plugin#27]
I think there should be a list of packages to be excluded.

For example, I'm using webpack's resolve alias
```js
alias: {
  src: path.resolve(__dirname, '../src'),
}
```
so basically I import all my app code starting from `src` - the plugin tries to install `src`, which is a problem

**Comment by radubrehar** [comment]
Also, using the `modulesDirectories` feature, so basically I have an `app_modules` folder, with a long list of local modules, which I require as if they are from node_modules. There should be an option to ignore those as well

**Comment by ericclemmons** [comment]
This is being tracked here:
#17
