### ISSUE TITLE
Feature request: support for webpack resolve.alias and resolve.root

### ISSUE THREAD

**Issue by acusti** [ericclemmons/npm-install-webpack-plugin#31]
I saw that this was mentioned in https://github.com/ericclemmons/npm-install-webpack-plugin/issues/13#issuecomment-178392747 and that it is currently being worked on (:clap:), but thought it might make sense to have it as it’s own issue for other people who have discovered the problem and want to know more about it. But please feel free to close this issue. Also, if there are any parts of the work to support `resolve.root` / `resolve.alias` that others could help with, I’d love to contribute!

On to the issue description:

-------

If you set up a webpack alias that you want to be able to use in your imports / requires, those aliases will be interpreted as referring to an external npm package, and this plugin will try to install it. For example, if you define an `svg` alias to point to a folder of svg files, and then want to require one of those files like `require('svg/icon.svg')`, you will have npm’s [svg package](https://www.npmjs.com/package/svg) installed into your repo.

**Comment by ericclemmons** [comment]
This should be resolved in #17!  Please re-open if this doesn't work with v3.0.0.
