### ISSUE TITLE
webpack-dev-server doesn't find packages right after they're installed

### ISSUE THREAD

**Issue by Phoenixmatrix** [ericclemmons/npm-install-webpack-plugin#34]
Not sure if it's a problem with my setup (well, it kind of has to be, since in your video it works fine, hah), but when the plugin installs a package automatically (which works very well), the webpack dev server throws an error that the package isn't there. If I ctrl+s the file again without any modification, then it works.

Kind of like if there was a race condition, and webpack tried to recompile too quickly. Any thought? This is on Windows, in case its OS specific (didn't try on OSX yet)

**Comment by prashcr** [comment]
I'm having the same issue on OSX

**Comment by ericclemmons** [comment]
Yep, this is an issue I was having as well.  Webpack's a confusing ball of mud, so it'll get fixed (eventually).  It was the sacrifice made to support `resolve.root` and `resolve.alias`.

**Comment by samuelbirch** [comment]
A quick fix could be to restart webpack? - If you could give any pointers as to where in my version i can hack that would be great.

**Comment by prashcr** [comment]
@samuelbirch Easier fix would be to just Ctrl-S any file being watched by WDS, so you don't have to startup the server again.

**Comment by samuelbirch** [comment]
@prashcr I could live with that, but that doesn't work for me. I have to restart webpack in order to get it working.

**Comment by prashcr** [comment]
@samuelbirch I'm taking a stab in the dark, but are you using WebStorm by any chance?

**Comment by ericclemmons** [comment]
I'd recommend using the [2.0.2](https://github.com/ericclemmons/npm-install-webpack-plugin/releases/tag/v2.0.2) release.

#29 will solve both the problems in `3.x` as well as keep the features missing in `2.x`, but require a significant amount of diving into code that only sokra knows.

**Comment by ericclemmons** [comment]
I think I have this mostly resolved in `v3.1.0`.  Please track that release.

There's really no way for me to get this working 100%.  Resolving loaders is **great**, but normal modules is **abysmal**.

It's as if Webpack's like "Sure, I'll let you install this dependency first, but _I already checked and it wasn't there so I don't care what you think!_".

Unless someone is very knowledgeable with Webpack's inner workings & can help resolve this (the `/example` is a fantastic testing ground), I'm on my own.
